### ISSUE TITLE
twitter thing should paste twitter link instead of tinyurl

### ISSUE THREAD

**Issue by KDKNFT** [Wobbley/gigantic-irc-bot#9]
20:14:15 <+Gigabot> <gg_unleashed> Stay up to date with @GoGigantic during PAX: http://t.co/Kzas0fTTjz [http://tinyurl.com/ogmnb8e]

**Comment by Wobbley** [comment]
No because the url is too long. People asked to have it removed. I can add
a source text or something instead.

**Comment by Wobbley** [comment]
I am taking suggestions to alternative solutios :p

**Comment by KDKNFT** [comment]
meh, sucks :( irccloud embeds the tweet when using the twitter link, now 
it just looks like an ugly paste :O(

On 6/03/2015 13:18, Dean Lozo wrote:

> No because the url is too long. People asked to have it removed. I can add
> a source text or something instead.
> On Mar 6, 2015 1:17 PM, "KenziDK" notifications@github.com wrote:
> 
> > 20:14:15 <+Gigabot> Stay up to date with @GoGigantic during PAX:
> > http://t.co/Kzas0fTTjz [http://tinyurl.com/ogmnb8e]
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Wobbley/gigantic-irc-bot/issues/9.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Wobbley/gigantic-irc-bot/issues/9#issuecomment-77550697.

---

L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by Wobbley** [comment]
Not everyone uses your fancy client! :p

**Comment by KDKNFT** [comment]
:'(

**Comment by KDKNFT** [comment]
nobody has complained about that on the hotstweet though

**Comment by Wobbley** [comment]
You just want it to be a twitter url so IRCCloud can make it pretty :p

**Comment by KDKNFT** [comment]
Yes I do!
